name: Autonomous ML Pipeline

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install fastapi uvicorn scikit-learn joblib pandas mlflow

    - name: Run ML pipeline
      run: |
        python main.py

    - name: Build Docker image
      run: |
        docker build -t autonomous-agent .

    - name: Run Docker container
      run: |
        docker run -d -p 8000:8000 autonomous-agent